apiVersion: v1
kind: Service
metadata:
  name: api-server-service
spec:
  type: NodePort
  ports:
  - port: 8080
    name: web-port
    protocol: TCP
    nodePort: 30380
    targetPort: 8080
  selector:
    app: api-server