apiVersion: v1
kind: Pod
metadata:
  name: api-server-pod
  labels:
    app: api-server
    tier: backend
spec:
  containers:
  - name: api-server
    image: ppy951/todo-api-server
    ports:
    - containerPort: 8080
    env:
    - name: PORT
      value: "8080"
    - name: DB_NAME
      value: go_todo
    - name: DB_USER
      value: root
    - name: DB_PASSWORD
      value: password
    - name: DB_HOST
      value: mysql-server-service
    - name: DB_PORT
      value: "3306"
