apiVersion: v1
kind: Pod
metadata:
  name: mysql-server-pod
  labels:
    app: mysql-server
    tier: backend
spec:
  containers:
  - name: mysql-server
    image: mysql:8
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: go_todo
